# TODO: add CURLPP_DEFINITIONS, CURLPP_EXECUTABLE, CURLPP_ROOT_DIR

find_package(CURL REQUIRED)

find_library(CURLPP_LIBRARIES NAMES curlpp)
find_path(CURLPP_INCLUDE_DIRS NAMES curlpp)

set(CURLPP_FOUND ${CURL_FOUND} ${CURLPP_LIBRARIES} AND ${CURLPP_INCLUDE_DIRS})
list(APPEND CURLPP_LIBRARIES ${CURL_LIBRARIES})
