
set(LIBCORO_BUILD_EXAMPLES OFF)
set(LIBCORO_BUILD_TESTS OFF)

add_subdirectory("${CMAKE_CURRENT_SOURCE_DIR}/libcoro")

set(LIBCORO_LIBRARIES libcoro)
set(LIBCORO_INCLUDE_DIRS ${CMAKE_CURRENT_SOURCE_DIR}/libcoro/include)
set(LIBCORO_FOUND ON)
